### ISSUE TITLE
Getting FFMPEG failed to download on a few posts

### ISSUE THREAD

**Issue by twist3dimages** [sim0n00ps/OF-DL#506] opened 2024-08-04 19:37 UTC
Here's the error message

![image](https://github.com/user-attachments/assets/147f3793-1a34-453c-822c-f3e3393ba068)

It works on the rest of the posts but I'm not sure why it's failing on these two. It's only happening for a specific user.

**Comment by melithine** [comment] 2024-08-06 11:11
This looks like a duplicate of #466. Please change your logging level to debug or verbose and attach the log to that issue.

**Closed by melithine** 2024-08-06 11:11 UTC
Labels: duplicate
