### ISSUE TITLE
FFmpeg failed to download when dealing with some Files

### ISSUE THREAD

**Issue by StrongstyleCode** [sim0n00ps/OF-DL#460] opened 2024-07-06 16:03 UTC
> FFmpeg failed to download https://cdn3.onlyfans.com/dash/files/7/7d/7d80699299ab021835239fb50ed092e2/0hmfdc61l87kjdqjqqclj.mpd
> Exception caught: Could not find file '<path insideOF-DLFolder>\Posts\Free\Videos\0hmfdc61l87kjdqjqqclj_source.mp4'.
> 
> StackTrace:    at System.IO.FileInfo.get_Length()
>    at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
>    at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String policy, String signature, String kvp, String url, String                                                                      String api_type, ProgressTask task, String filename

   
   Seems like it's not able to parse whatever is returned from CDRM-Project? this is inside the logs
   
   

> StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String policy, String signature, String kvp, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String filenameFormat, List postInfo, Medium postMedia, Author author, Dictionary`2 users)
2024-07-06 12:49:37.292 -03:00 [ERR] ffmpeg version 7.0.1-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Unrecognized option '->\n\n\n'.
Error splitting the argument list: Option not found
   

Strangely enough it appears some DRM items are downloading

**Comment by sim0n00ps** [comment] 2024-07-07 20:25
To me that seems like the command the code is crafting seems to be including some "\n" characters so that might be the problem. This might also fix a lot of other problems as well.

**Comment by melithine** [comment] 2024-09-01 10:10
I'm going to flag this as a dupe of #466 and close this out.

**Closed by melithine** 2024-09-01 10:10 UTC
Labels: bug, help wanted
