### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ZincStoat** [sim0n00ps/OF-DL#523] opened 2024-08-14 19:30 UTC
Using 1.7.71. Updated auth.json using the plugin. Downloads from individual creators seem fine, but Download Purchased Tab breaks with the following:
![image](https://github.com/user-attachments/assets/23783ae8-669d-4095-8bcc-2e9bf1ec41e6)

Last few lines of the log with LoggingLevel set to "Debug" read

`
2024-08-14 19:19:27.661 +01:00 [DBG] Calling BuildHttpRequestMessage
2024-08-14 19:19:27.661 +01:00 [DBG] Calling GetDynamicHeaders
2024-08-14 19:19:27.661 +01:00 [DBG] Path: /api2/v2/users/list?x[]=17432550
2024-08-14 19:19:27.661 +01:00 [DBG] Query Params: ?
2024-08-14 19:19:27.662 +01:00 [DBG] Full request URL: https://onlyfans.com/api2/v2/users/list?x[]=17432550?
2024-08-14 19:19:27.900 +01:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetPurchasedTabUsers(String endpoint, IDownloadConfig config, Dictionary`2 users)
2024-08-14 19:19:27.904 +01:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Program.DownloadAllData(APIHelper m_ApiHelper, Auth Auth, Config Config)
   at OF_DL.Program.Main(String[] args)
`

Not sure where it's going wrong, but one error breaks the whole download, which is not ideal.

**Comment by melithine** [comment] 2024-08-20 16:18
Looks like onlyfans changed something. We'll have to look into it and make a new release.

**Comment by Wingzer01** [comment] 2024-08-20 17:04
Normal posts are downloaded without any problems
Only message posts display the corresponding error message

Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetPaidMessage(String endpoint, String folder, IDownloadConfig config)

**Comment by melithine** [comment] 2024-08-20 17:08
It's not just messages and not just the purchased tab. Videos seem fine but scraping a single post with just images failed when I was testing.

**Comment by RhysG0011** [comment] 2024-08-20 17:13
Its because they've changed the JSON responses I am working on a fix now please be patient

**Comment by sim0n00ps** [comment] 2024-08-20 17:14
Its because they changed the JSON responses slightly, I'm working on a fix please be patient

**Comment by djmarioka** [comment] 2024-08-21 07:40
> Its because they changed the JSON responses slightly, I'm working on a fix please be patient

Thanks a lot :)

**Comment by bezaaas** [comment] 2024-08-21 08:20
> Its because they changed the JSON responses slightly, I'm working on a fix please be patient

Do you have any news? 🙏

**Comment by sim0n00ps** [comment] 2024-08-21 08:46
I've fixed the problem and need to iron out a few things, then it will be ready for release later today hopefully

**Comment by Astercholik** [comment] 2024-08-21 20:08
Any news on whether a fix will be released today?

**Comment by sim0n00ps** [comment] 2024-08-21 20:14
https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.72

**Comment by ZincStoat** [comment] 2024-08-22 03:58
I've been away for a few days, and got back to find this issue closed. I've updated to 1.7.73 though and I'm getting the exact same results I quoted when I submitted the report.

**Comment by AnthonySteer** [comment] 2024-08-22 04:26
> I've been away for a few days, and got back to find this issue closed. I've updated to 1.7.73 though and I'm getting the exact same results I quoted when I submitted the report.

I have updated to 1.7.7**2** and, for me, the fix is working. Maybe two different causes with the same manifestation?  I think this fix fixed the general issue of _Object reference not set to an instance of an object_ which started happening regardless of which part of the site was being downloaded, but your issue was more specific to purchased.

**Comment by melithine** [comment] 2024-08-22 05:00
> I've been away for a few days, and got back to find this issue closed. I've updated to 1.7.73 though and I'm getting the exact same results I quoted when I submitted the report.

Reopened. Can you please provide a fresh debug log, the whole thing? Seems like your issue may have been separate than the one that was affecting everyone else, despite literally having the exact same error message. I tried my purchased tab and it was without issue.

**Comment by ZincStoat** [comment] 2024-08-22 06:35
Here y'go.
[OFDL20240822.zip](https://github.com/user-attachments/files/16706340/OFDL20240822.zip)

**Comment by djmarioka** [comment] 2024-08-22 07:39
Hi, the new update looks like it doesn't work.

Could anybody fix it?.

Thanks.

**Comment by melithine** [comment] 2024-08-22 07:51
> Hi, the new update looks like it doesn't work.
> 
> Could anybody fix it?.
> 
> Thanks.

If you have the exact same issue as before, please attach a debug log. Otherwise please file a new issue with details beyond "doesn't work".

**Comment by sim0n00ps** [comment] 2024-08-22 23:23
If you can try https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.74 and let me know if that fixes it. It should fix the null ref issue that most people will be seeing, I'll leave this issue open for now

**Comment by ZincStoat** [comment] 2024-08-22 23:51
> If you can try https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.74 and let me know if that fixes it. It should fix the null ref issue that most people will be seeing, I'll leave this issue open for now

Same result I'm afraid. I'm _guessing_ it's barfing on just one file and/or creator, and that's causing the whole Purchased Tab scan to abort. Latest debug log attached. Thanks for looking into this.

[OFDL20240823.zip](https://github.com/user-attachments/files/16720209/OFDL20240823.zip)

**Comment by CaptainKoons** [comment] 2024-08-23 06:50
> If you can try https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.74 and let me know if that fixes it. It should fix the null ref issue that most people will be seeing, I'll leave this issue open for now

I've tried V1.7.74 on 6 creators. Works perfect for me. Many thanks!

**Comment by Wingzer01** [comment] 2024-08-23 07:31
> If you can try https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.74 and let me know if that fixes it. It should fix the null ref issue that most people will be seeing, I'll leave this issue open for now

It's going well

**Comment by sim0n00ps** [comment] 2024-08-23 07:38
> > If you can try https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.74 and let me know if that fixes it. It should fix the null ref issue that most people will be seeing, I'll leave this issue open for now
> 
> Same result I'm afraid. I'm _guessing_ it's barfing on just one file and/or creator, and that's causing the whole Purchased Tab scan to abort. Latest debug log attached. Thanks for looking into this.
> 
> [OFDL20240823.zip](https://github.com/user-attachments/files/16720209/OFDL20240823.zip)
> 

Alright I think the only way I'm going to be able to reproduce this is with your actual Auth because I can't reproduce it on my account and it seems others don't have the same issue. Probably best to contact me on discord if you have it

**Comment by fidelio959** [comment] 2024-08-23 15:30
I tried the latest version and is working fine. I can download single posts and full scrape. Thanks for your great work!!

**Closed** 2024-09-01 10:12 UTC
Labels: release follow-up
