### ISSUE TITLE
1.7.28 closes after run

### ISSUE THREAD

**Issue by miglety** [sim0n00ps/OF-DL#131] opened 2023-08-21 10:47 UTC
I havent been able to catch it in the act yet but it appears that once a run completes the app just closes whereas that was not how it worked pre 1.7.28. It appears its completing a run as i have updated content but every time i go back to check the script it is closed and i have to re-open it.

**Comment by Kameshennyn** [comment] 2023-08-22 00:16
![2023-08-22](https://github.com/sim0n00ps/OF-DL/assets/100891073/ec2ac6fd-156a-451c-ad49-ed0744a76ac2)
I got the same issue but only with this creator, also I don't have any "rhysd" user in my system x)

**Comment by sim0n00ps** [comment] 2023-08-22 20:39
Is this using the latest version?

**Comment by miglety** [comment] 2023-08-22 20:41
@sim0n00ps i am running version 1.7.28

**Comment by sim0n00ps** [comment] 2023-08-22 21:25
Well the user you see is actually mine from my pc, I have modified the spectre-console library and referenced it within the project itself. As far as I'm aware the changes I made are not the cause of the error.

**Comment by miglety** [comment] 2023-08-22 22:10
@sim0n00ps the image is not mine thats another users. I havent been able to catch it close in the act, just know that its closed after a certain period of time.

**Comment by Kameshennyn** [comment] 2023-08-23 01:35
It's my pic but must be sort of the same issue,
you should try to open it directly from PowerShell,
so you'll end up with the prompt and the error message like I did instead of just closing itself

**Closed** 2023-09-15 19:46 UTC
