### ISSUE TITLE
Exception Caught: Could not find file

### ISSUE THREAD

**Issue by Womack123** [sim0n00ps/OF-DL#367] opened 2024-05-30 14:02 UTC
It says: 

 FFmpeg failed to download https://cdn3.onlyfans.com/Downloading 2 Messages ----------------------------------------   0%1o.mpd
                                                                    Exception caught: Could not find file 'D:\Downloads\OF.DL.V1.7.58\__user_data__\sites\OnlyFans\natalie_roser\Messages\Free\Videos\0hq7p2hlonldube3anm1o_source.mp4'.
StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path, Boolean showScrapeSize, Config config)
   at OF_DL.Helpers.DownloadHelper.DownloadMessageDRMVideo(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask tas                                                                    mUser fromUser, Dictionary`2 users, Config config, BDownloading 2 Messages ----------------------------------------  50%

Messages Already Downloaded: 2 New Messages Downloaded: 0

**Comment by badbeezy** [comment] 2024-05-31 19:12
I'm having this same issue with DRM files unfortunately.

**Comment by melithine** [comment] 2024-06-06 23:56
Try the newest release and maybe upgrading ffmpeg.exe.

**Comment by bezaaas** [comment] 2024-06-08 22:12
I'm having the same issue with the latest ffmpeg. 
Only some of the DRM videos cannot be downloaded. Most DRM ones are downloaded, but sometimes they are not.

**Comment by oqpsk** [comment] 2024-06-11 06:43
I'm having this same issue with DRM files as well. Latest release + latest ffmpeg version.

**Comment by lukaeber** [comment] 2024-06-21 17:35
Also having the same issue. Only for certain files.

**Comment by melithine** [comment] 2024-07-31 18:42
I believe this is a duplicate of #466.

**Closed by melithine** 2024-07-31 18:42 UTC
