### ISSUE TITLE
Is it possible to get all media into 1 folder?

### ISSUE THREAD

**Issue by perling55** [sim0n00ps/OF-DL#426] opened 2024-06-21 21:12 UTC
I have looked at the config, I cant find it, if its even possible to change the subfolders. 

If its not possible it would be a feature suggestion.

**Comment by melithine** [comment] 2024-06-21 21:43
Duplicate of https://github.com/sim0n00ps/OF-DL/issues/296

**Closed by melithine** 2024-06-21 21:43 UTC
