### ISSUE TITLE
Exception caught: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by djmarioka** [sim0n00ps/OF-DL#531] opened 2024-08-21 07:39 UTC
Hi,

I'm receiving this error since 1 or 2 days ago:

<img width="667" alt="image" src="https://github.com/user-attachments/assets/786a452e-6c6e-4793-9a5b-5f5c5516831f">

and I can't download anything else.

Could anybody help me to fix this issue?.

Thanks.

**Comment by melithine** [comment] 2024-08-21 07:53
Duplicate of #523

**Closed by melithine** 2024-08-21 07:53 UTC
