### ISSUE TITLE
Can't get any post from today

### ISSUE THREAD

**Issue by Kameshennyn** [sim0n00ps/OF-DL#528] opened 2024-08-20 16:44 UTC
Hey, I'm getting this error for every account :x

Getting Paid Posts
Found 0 Paid Posts
Getting Posts
Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetPosts(String endpoint, String folder, IDownloadConfig config, List`1 paid_post_ids)
Found 0 Posts
Getting Archived Posts
Found 0 Archived Posts
Getting Streams
Found 0 Streams
Getting Stories
Found 0 Stories
Getting Highlights
Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetMedia(MediaType mediatype, String endpoint, String username, String folder, IDownloadConfig config, List`1 paid_post_ids)
Found 0 Highlights
Getting Messages
Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetMessages(String endpoint, String folder, IDownloadConfig config)
Found 0 Messages
Getting Paid Messages
Found 0 Paid Messages

██████████████████████████████████████████████████████████████████████████████████████████████████████████████████

■ Paid Posts 0        ■ Posts 0    ■ Archived 0    ■ Streams 0    ■ Stories 0    ■ Highlights 0    ■ Messages 0
■ Paid Messages 0

**Comment by CorpseBloom** [comment] 2024-08-20 16:55
Having a similar issue, which is interesting because it was working this morning, and then a scrape got to about 53% and just stopped. Assuming the problem was on my end, I close the exe, rebooted my computer, and then came back and now this error occurs.

**Comment by ajq11** [comment] 2024-08-20 16:56
I'm having the same issue today. Worked last night.

**Comment by melithine** [comment] 2024-08-20 17:03
Duplicate of #523

**Closed by melithine** 2024-08-20 17:03 UTC
