### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by jadenquinn** [sim0n00ps/OF-DL#526] opened 2024-08-18 03:25 UTC
I had this issue on an older version, so I updated, but gave the same result. 
No idea why Github is messing up the formatting here, I just pasted what I saw in the log.

Downloading 2316 Posts ----------------------------------------   4%

                                                                    FFmpeg failed to download https://cdn3.onlyfans.com/dash/files/0/09/09fd950f30ee206d1572aef49af71f30/0hrkr96gcse8a1bo4n5yl.mpd
Exception caught: Could not find file 'I:\OFDLV1.7.71\__user_data__\sites\OnlyFans\ceciliaxemily\Posts\Free\Videos\0hrkr96gcse8a1bo4n5yl_source.mp4'.

                             StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String policy, String signature, String kvp, String url, String                                                                      String api_type, ProgressTask task, String filename
Downloading 2316 Posts ----------------------------------------   4% users)

                                                                    FFmpeg failed to download https://cdn3.onlyfans.com/dash/files/a/ac/ac77ccae2363cb81e4a6b23a72237c29/0hs1yskofzp321xexiiak.mpd
Exception caught: Could not find file 'I:\OFDLV1.7.71\__user_data__\sites\OnlyFans\ceciliaxemily\Posts\Free\Videos\0hs1yskofzp321xexiiak_source.mp4'.

                             StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String policy, String signature, String kvp, String url, String                                                                      String api_type, ProgressTask task, String filename
Downloading 2316 Posts ----------------------------------------   7% users)

**Comment by melithine** [comment] 2024-08-20 17:01
This is a duplicate of #466 .

**Closed by melithine** 2024-08-20 17:01 UTC
