### ISSUE TITLE
[Bug] `RenameExistingFilesWhenCustomFormatIsSelected`  does not rename already saved media.

### ISSUE THREAD

**Issue by hydr0homiee** [sim0n00ps/OF-DL#599] opened 2024-10-11 00:51 UTC
The `RenameExistingFilesWhenCustomFormatIsSelected` option seems to be broken. I've changed the custom file name format and switched that param to `true` but I don't see any of the already downloaded content being renamed.

Windows 10 Pro
OF-DF v1.7.79

Debug logs: [OFDL20241010.txt](https://github.com/user-attachments/files/17335927/OFDL20241010.txt)

**Comment by melithine** [comment] 2024-10-11 01:40
Dupe of #345

**Closed by melithine** 2024-10-11 01:40 UTC

**Comment by hydr0homiee** [comment] 2024-10-11 01:46
My bad, didn't know it was already reported

**Comment by melithine** [comment] 2024-10-11 01:49
No worries, I try to keep up with triaging the issues as best as I can when I have time.
