### ISSUE TITLE
Add media file download support for a date range

### ISSUE THREAD

**Issue by erickcasita** [sim0n00ps/OF-DL#578] opened 2024-09-23 15:43 UTC
An option should be added to be able to download media content within a date range. 

This is so that users who are-subscriber can continue downloading from the last date they were active.

Thanks.

**Comment by melithine** [comment] 2024-09-23 16:47
Duplicate of #499, although your use case sounds more like IncrementalMode would suffice.

**Closed by melithine** 2024-09-23 16:47 UTC
