### ISSUE TITLE
Unable to download DRM content

### ISSUE THREAD

**Issue by divakar123** [sim0n00ps/OF-DL#409] opened 2024-06-13 12:54 UTC
having this Error

using the latest version of FFMPEG 

 FFmpeg failed to download https://cdn3.onlyfans.com/dash/files/5/54/54ec797d42bec539e478a2ac11f496de/0hplbz9oaultnl4kf71pn.mpd
Exception caught: Could not find file 'C:\Users\Administrator\Downloads\OF.DL.V1.7.60\__user_data__\sites\OnlyFans\masterlucca\Posts\Free\Videos\0hplbz9oaultnl4kf71pn_source.mp4'.

                                                           StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String policy, String signature, String kvp, String url, String

**Comment by badbeezy** [comment] 2024-06-13 16:44
I was able to download DRM by using OF-DRM V1.10. Unfortunately that no longer works and crashes on opening since the OF site updated yesterday. I get the same errors as above on DRM files on OF-DL and I believe the crashing on OF DRM is related, so that one needs an update as well.

**Comment by purpleemoji** [comment] 2024-06-14 16:01
Having the same issue with OF DL V1.7.60.

Sorry for my ignorance. I haven't updated OF DL since V1.44 which I successfully used up until two weeks ago.
When did the OF-DRM fork come about? Does OF DL still support DRM content? I see there are fewer parameters in the auth file than there used to be on the older versions of OF-DL.

**Comment by melithine** [comment] 2024-06-14 21:04
> Having the same issue with OF DL V1.7.60.
> 
> Sorry for my ignorance. I haven't updated OF DL since V1.44 which I successfully used up until two weeks ago. When did the OF-DRM fork come about? Does OF DL still support DRM content? I see there are fewer parameters in the auth file than there used to be on the older versions of OF-DL.

OF-DRM is separate and meant as a streamlined version, but isn't as actively developed. With OF DL, 1.7.60, make sure you have the rules.json alongside auth.json, and remember that auth failures usually invalidate your session, so auth.json needs to be updated each time.

**Comment by badbeezy** [comment] 2024-06-18 19:56
> > Having the same issue with OF DL V1.7.60.
> > Sorry for my ignorance. I haven't updated OF DL since V1.44 which I successfully used up until two weeks ago. When did the OF-DRM fork come about? Does OF DL still support DRM content? I see there are fewer parameters in the auth file than there used to be on the older versions of OF-DL.
> 
> OF-DRM is separate and meant as a streamlined version, but isn't as actively developed. With OF DL, 1.7.60, make sure you have the rules.json alongside auth.json, and remember that auth failures usually invalidate your session, so auth.json needs to be updated each time.

With OF-DL, all non drm downloads fine. but with drm, I get the above error. When downloading the DRM with OF-DRM, it seems to work with smaller DRM videos, but i get the same error as above when attempting to download larger videos. What could be the cause of this?

**Comment by btiplitz** [comment] 2024-06-24 02:27
I think I'm getting a similar issue with 1.7.60.  This does not happen on all messages, just a few
FFmpeg failed to download https://cdn3.onlyfans.com/dash/files/b/b9/<hash>/<file>.mpd
Exception caught: Could not find file 'C:\Users\local\Downloads\OF.DL.V1.7.60\__user_data__\sites\OnlyFans\<creator>\Messages\Paid\Videos\<file>_source.mp4'.

StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path)
   at OF_DL.Helpers.DownloadHelper.DownloadPurchasedMessageDRMVideo(String policy, String signature, String kvp, String                                                                                                            filenameForma

**Comment by melithine** [comment] 2024-07-31 18:27
This seems like a dupe of #466.

**Closed by melithine** 2024-07-31 18:27 UTC
