### ISSUE TITLE
RenameExistingFilesWhenCustomFormatIsSelected does not work with drm protected post videos

### ISSUE THREAD

**Issue by michamisch** [sim0n00ps/OF-DL#568] opened 2024-09-16 12:28 UTC
Some files did not get renamed on my Windows System especially files starting with 0 in the name.
After some looking around in the code (DownloadHelper.cs) I found out that the strings are constructed like this:
string fullPathWithTheServerFileName = $“{folder}{path}/{serverFilename}{extension}”;
The path will then be converted to windows \0 wich is a null terminator in my case.
This in turn causes the File.Exists call to fail.
My C# coding skills are unfortunately too bad, otherwise I would have fixed this myself
 

**Edit:**
First i though this is a \0 problems, but after looking at the source code i found that the logic for renaming drm videos is missing

**Comment by sim0n00ps** [comment] 2024-09-18 10:36
If you know what needs to be changed then create a Pull Request and I'll merge it

**Comment by melithine** [comment] 2024-09-23 22:02
This is a duplicate of #345, please continue there.

**Closed by melithine** 2024-09-23 22:02 UTC
Labels: duplicate
